In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import time

from numpy.lib.recfunctions import join_by
from sympy import sequence

In [7]:
text=open('khayyam.txt','rb').read().decode('utf-8')
text[:10]

'|برخیز بُت'

In [9]:
vocabolaries=sorted(set(text))
vocabolaries[:10]

['\n', '\r', ' ', '!', ':', '|', '\xa0', '«', '»', '،']

In [10]:
len(vocabolaries)

53

In [11]:
char2index={u:i for i,u in enumerate(vocabolaries) }
index2char=np.array(vocabolaries)
char2index

{'\n': 0,
 '\r': 1,
 ' ': 2,
 '!': 3,
 ':': 4,
 '|': 5,
 '\xa0': 6,
 '«': 7,
 '»': 8,
 '،': 9,
 '؟': 10,
 'آ': 11,
 'أ': 12,
 'ئ': 13,
 'ا': 14,
 'ب': 15,
 'ت': 16,
 'ث': 17,
 'ج': 18,
 'ح': 19,
 'خ': 20,
 'د': 21,
 'ذ': 22,
 'ر': 23,
 'ز': 24,
 'س': 25,
 'ش': 26,
 'ص': 27,
 'ض': 28,
 'ط': 29,
 'ظ': 30,
 'ع': 31,
 'غ': 32,
 'ف': 33,
 'ق': 34,
 'ل': 35,
 'م': 36,
 'ن': 37,
 'ه': 38,
 'و': 39,
 'َ': 40,
 'ُ': 41,
 'ِ': 42,
 'ّ': 43,
 'ْ': 44,
 'ٔ': 45,
 'پ': 46,
 'چ': 47,
 'ژ': 48,
 'ک': 49,
 'گ': 50,
 'ۀ': 51,
 'ی': 52}

In [12]:
text_as_integer=np.array([char2index[c] for c in text])
text_as_integer

array([ 5, 15, 23, ..., 10,  1,  0], shape=(22813,))

In [13]:
char_dataset=tf.data.Dataset.from_tensor_slices(text_as_integer)
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [16]:
for i in char_dataset:
    print(index2char[i.numpy()])

|
ب
ر
خ
ی
ز
 
ب
ُ
ت
ا
،
 
ب
ی
ا
 
ز
 
ب
ه
ر
 
د
ل
 
م
ا



|
ح
ل
 
ک
ن
 
ب
ه
 
ج
م
ا
ل
 
خ
و
ی
ش
ت
ن
 
م
ش
ک
ل
 
م
ا



|
ی
ک
 
ک
و
ز
ه
 
ش
ر
ا
ب
 
ت
ا
 
ب
ه
 
ه
م
 
ن
و
ش
 
ک
ن
ی
م



|
ز
آ
ن
 
پ
ی
ش
 
ک
ه
 
ک
و
ز
ه
 
ه
ا
 
ک
ن
ن
د
 
ا
ز
 
گ
ِ
ل
 
م
ا



|
چ
و
ن
 
ع
ه
د
ه
 
ن
م
ی
 
ش
و
د
 
ک
س
ی
 
ف
ر
د
ا
 
ر
ا



|
ح
ا
ل
ی
 
خ
و
ش
 
د
ا
ر
 
ا
ی
ن
 
د
ل
ِ
 
پ
ر
 
س
و
د
ا
 
ر
ا



|
م
ِ
ی
 
ن
و
ش
 
ب
ه
 
م
ا
ه
ت
ا
ب
 
ا
ی
 
م
ا
ه
 
ک
ه
 
م
ا
ه



|
ب
س
ی
ا
ر
 
ب
ت
ا
ب
د
 
و
 
ن
ی
ا
ب
د
 
م
ا
 
ر
ا



|
ق
ر
آ
ن
 
ک
ه
 
م
ه
ی
ن
 
ک
ل
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
گ
ه
 
گ
ا
ه
 
ن
ه
 
ب
ر
 
د
و
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
ب
ر
 
گ
ِ
ر
د
ِ
 
پ
ی
ا
ل
ه
،
 
آ
ی
ت
ی
 
ه
س
ت
 
م
ق
ی
م



|
ک
ا
ن
د
ر
 
ه
م
ه
 
ج
ا
 
م
د
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
گ
ر
 
م
ِ
ی
 
ن
خ
و
ر
ی
 
ط
ع
ن
ه
 
م
ز
ن
 
م
س
ت
ا
ن
 
ر
ا



|
ب
ن
ی
ا
د
 
م
ک
َ
ن
 
ت
و
 
ح
ی
ل
ه
 
و
 
د
س
ت
ا
ن
 
ر
ا



|
ت
و
 
غ
ر
ه
 
ب
د
ا
ن
 
م
ش
و
 
ک
ه
 
م
ِ
ی
 
م
ی
 
ن
خ
و
ر
ی



|
ص
د
 
ل
ق
م
ه
 
خ
و
ر
ی
 
ک
ه
 
م
ِ
ی
 

In [18]:
sequence=char_dataset.batch(30,drop_remainder=True)
sequence

<_BatchDataset element_spec=TensorSpec(shape=(30,), dtype=tf.int64, name=None)>

In [25]:
for i in sequence.take(3):
    print('---->',''.join(index2char[i.numpy()]))

----> |برخیز بُتا، بیا ز بهر دل ما

----> |حل کن به جمال خویشتن مشکل ما
----> 
|یک کوزه شراب تا به هم نوش کن


In [30]:
def sit(batch):
    input_txt=batch[:-1]
    target_txt=batch[1:]
    return input_txt,target_txt
dataset=sequence.map(sit)

In [31]:
dataset

<_MapDataset element_spec=(TensorSpec(shape=(29,), dtype=tf.int64, name=None), TensorSpec(shape=(29,), dtype=tf.int64, name=None))>

In [33]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(29,), dtype=int64, numpy=
array([ 5, 15, 23, 20, 52, 24,  2, 15, 41, 16, 14,  9,  2, 15, 52, 14,  2,
       24,  2, 15, 38, 23,  2, 21, 35,  2, 36, 14,  1])>, <tf.Tensor: shape=(29,), dtype=int64, numpy=
array([15, 23, 20, 52, 24,  2, 15, 41, 16, 14,  9,  2, 15, 52, 14,  2, 24,
        2, 15, 38, 23,  2, 21, 35,  2, 36, 14,  1,  0])>)


In [34]:
for i in dataset.take(1):
    print(''.join(index2char[i[0].numpy()]))
    print(''.join(index2char[i[1].numpy()]))


|برخیز بُتا، بیا ز بهر دل ما
برخیز بُتا، بیا ز بهر دل ما



In [35]:
dataset=dataset.batch(64,drop_remainder=True)
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(64, 29), dtype=tf.int64, name=None), TensorSpec(shape=(64, 29), dtype=tf.int64, name=None))>