In [22]:
import tensorflow as tf
import numpy as np
import pandas as pd
import time
from tensorflow.keras.models import Sequential,Model
from numpy.lib.recfunctions import join_by
from sympy import sequence



In [23]:
text=open('khayyam.txt','rb').read().decode('utf-8')
text[:10]

'|زاهدی را '

In [24]:
vocabolaries=sorted(set(text))
vocabolaries[:10]

['\n', '\r', ' ', '!', ':', '|', '«', '»', '،', '؟']

In [25]:
len(vocabolaries)

57

In [26]:
char2index={u:i for i,u in enumerate(vocabolaries) }
index2char=np.array(vocabolaries)
char2index

{'\n': 0,
 '\r': 1,
 ' ': 2,
 '!': 3,
 ':': 4,
 '|': 5,
 '«': 6,
 '»': 7,
 '،': 8,
 '؟': 9,
 'ء': 10,
 'آ': 11,
 'ؤ': 12,
 'ئ': 13,
 'ا': 14,
 'ب': 15,
 'ة': 16,
 'ت': 17,
 'ث': 18,
 'ج': 19,
 'ح': 20,
 'خ': 21,
 'د': 22,
 'ذ': 23,
 'ر': 24,
 'ز': 25,
 'س': 26,
 'ش': 27,
 'ص': 28,
 'ض': 29,
 'ط': 30,
 'ظ': 31,
 'ع': 32,
 'غ': 33,
 'ف': 34,
 'ق': 35,
 'ل': 36,
 'م': 37,
 'ن': 38,
 'ه': 39,
 'و': 40,
 'ي': 41,
 'ً': 42,
 'َ': 43,
 'ُ': 44,
 'ِ': 45,
 'ّ': 46,
 'ْ': 47,
 'ٓ': 48,
 'ٔ': 49,
 'ٰ': 50,
 'پ': 51,
 'چ': 52,
 'ژ': 53,
 'ک': 54,
 'گ': 55,
 'ی': 56}

In [27]:
text_as_integer=np.array([char2index[c] for c in text])
text_as_integer

array([ 5, 25, 14, ..., 37,  1,  0], shape=(195185,))

In [28]:
char_dataset=tf.data.Dataset.from_tensor_slices(text_as_integer)
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [29]:
for i in char_dataset:
    print(index2char[i.numpy()])

|
ز
ا
ه
د
ی
 
ر
ا
 
گ
ف
ت
 
ی
ا
ر
ی
 
د
ر
 
ع
م
ل



|
ک
م
 
گ
ر
ی
 
ت
ا
 
چ
ش
م
 
ر
ا
 
ن
ا
ی
د
 
خ
ل
ل



|
گ
ف
ت
 
ز
ا
ه
د
 
ا
ز
 
د
و
 
ب
ی
ر
و
ن
 
ن
ی
س
ت
 
ح
ا
ل



|
چ
ش
م
 
ب
ی
ن
د
 
ی
ا
 
ن
ب
ی
ن
د
 
آ
ن
 
ج
م
ا
ل



|
گ
ر
 
ب
ب
ی
ن
د
 
ن
و
ر
 
ح
ق
 
خ
و
د
 
چ
ه
 
غ
م
س
ت



|
د
ر
 
و
ص
ا
ل
 
ح
ق
 
د
و
 
د
ی
د
ه
 
چ
ه
 
ک
م
س
ت



|
و
ر
 
ن
خ
و
ا
ه
د
 
د
ی
د
 
ح
ق
 
ر
ا
 
گ
و
 
ب
ر
و



|
ا
ی
ن
 
چ
ن
ی
ن
 
چ
ش
م
 
ش
ق
ی
 
گ
و
 
ک
و
ر
 
ش
و



|
غ
م
 
م
خ
و
ر
 
ا
ز
 
د
ی
د
ه
،
 
ک
ا
ن
 
ع
ی
س
ی
 
ت
ر
ا
س
ت



|
چ
پ
 
م
ر
و
 
ت
ا
 
ب
خ
ش
د
ت
 
د
و
 
چ
ش
م
 
ر
ا
س
ت



|
ع
ی
س
ی
 
ر
و
ح
 
ت
و
 
ب
ا
 
ت
و
 
ح
ا
ض
ر
س
ت



|
ن
ص
ر
ت
 
ا
ز
 
و
ی
 
خ
و
ا
ه
 
ک
و
 
خ
و
ش
 
ن
ا
ص
ر
س
ت



|
ل
ی
ک
 
ب
ی
گ
ا
ر
 
ت
ن
 
پ
ر
 
ا
س
ت
خ
و
ا
ن



|
ب
ر
 
د
ل
 
ع
ی
س
ی
 
م
ن
ه
 
ت
و
 
ه
ر
 
ز
م
ا
ن



|
ه
م
چ
و
 
آ
ن
 
ا
ب
ل
ه
 
ک
ه
 
ا
ن
د
ر
 
د
ا
س
ت
ا
ن



|
ذ
ک
ر
 
ا
و
 
ک
ر
د
ی
م
 
ب
ه
ر
 
ر
ا
س
ت
ا
ن



|
ز
ن
د
گ
ی
 
ت
ن
 
م
ج
و
 
ا
ز
 
ع
ی
س
ی
 
ا
ت



|
ک
ا
م
 
ف
ر
ع
و
ن
ی
 
م
خ
و
ا
ه
 

In [30]:
sequence=char_dataset.batch(101,drop_remainder=True)
sequence

<_BatchDataset element_spec=TensorSpec(shape=(101,), dtype=tf.int64, name=None)>

In [31]:
for i in sequence.take(3):
    print('---->',''.join(index2char[i.numpy()]))

----> |زاهدی را گفت یاری در عمل
|کم گری تا چشم را ناید خلل
|گفت زاهد از دو بیرون نیست حال
|چشم بیند یا ن
----> بیند آن جمال
|گر ببیند نور حق خود چه غمست
|در وصال حق دو دیده چه کمست
|ور نخواهد دید حق را گو برو
----> 
|این چنین چشم شقی گو کور شو
|غم مخور از دیده، کان عیسی تراست
|چپ مرو تا بخشدت دو چشم راست
|عیسی ر


In [32]:
def sit(batch):
    input_txt=batch[:-1]
    target_txt=batch[1:]
    return input_txt,target_txt
dataset=sequence.map(sit)

In [33]:
dataset

<_MapDataset element_spec=(TensorSpec(shape=(100,), dtype=tf.int64, name=None), TensorSpec(shape=(100,), dtype=tf.int64, name=None))>

In [34]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([ 5, 25, 14, 39, 22, 56,  2, 24, 14,  2, 55, 34, 17,  2, 56, 14, 24,
       56,  2, 22, 24,  2, 32, 37, 36,  1,  0,  5, 54, 37,  2, 55, 24, 56,
        2, 17, 14,  2, 52, 27, 37,  2, 24, 14,  2, 38, 14, 56, 22,  2, 21,
       36, 36,  1,  0,  5, 55, 34, 17,  2, 25, 14, 39, 22,  2, 14, 25,  2,
       22, 40,  2, 15, 56, 24, 40, 38,  2, 38, 56, 26, 17,  2, 20, 14, 36,
        1,  0,  5, 52, 27, 37,  2, 15, 56, 38, 22,  2, 56, 14,  2])>, <tf.Tensor: shape=(100,), dtype=int64, numpy=
array([25, 14, 39, 22, 56,  2, 24, 14,  2, 55, 34, 17,  2, 56, 14, 24, 56,
        2, 22, 24,  2, 32, 37, 36,  1,  0,  5, 54, 37,  2, 55, 24, 56,  2,
       17, 14,  2, 52, 27, 37,  2, 24, 14,  2, 38, 14, 56, 22,  2, 21, 36,
       36,  1,  0,  5, 55, 34, 17,  2, 25, 14, 39, 22,  2, 14, 25,  2, 22,
       40,  2, 15, 56, 24, 40, 38,  2, 38, 56, 26, 17,  2, 20, 14, 36,  1,
        0,  5, 52, 27, 37,  2, 15, 56, 38, 22,  2, 56, 14,  2, 38])>)


In [35]:
for i in dataset.take(1):
    print(''.join(index2char[i[0].numpy()]))
    print(''.join(index2char[i[1].numpy()]))


|زاهدی را گفت یاری در عمل
|کم گری تا چشم را ناید خلل
|گفت زاهد از دو بیرون نیست حال
|چشم بیند یا 
زاهدی را گفت یاری در عمل
|کم گری تا چشم را ناید خلل
|گفت زاهد از دو بیرون نیست حال
|چشم بیند یا ن


In [36]:
dataset=dataset.batch(64,drop_remainder=True)
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

In [37]:
vocabulary_size=len(vocabolaries)
embding_dim=256
rnn_units=1024

In [38]:
from tensorflow.keras.layers import Embedding,Dense,GRU
model = Sequential()
model.add(Embedding(input_dim=vocabulary_size,output_dim=25)),
model.add(GRU(rnn_units, return_sequences=True)),
model.add(Dense(vocabulary_size))

In [39]:
for input_text,target_text in dataset.take(1):
    output=model.predict(input_text)
    print(output[0])

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step
[[ 2.8175013e-03 -5.3226185e-04  3.3565252e-03 ... -3.1567621e-03
   6.2571443e-04 -1.2451001e-03]
 [ 7.9092610e-04  2.5158504e-03  3.9309915e-04 ... -3.8301460e-03
  -2.2878519e-03 -3.6741735e-03]
 [ 2.5701481e-03  5.7749724e-04  1.2719432e-03 ... -4.6338914e-03
  -1.4856802e-03  8.8972703e-04]
 ...
 [-1.7969580e-03  6.5175665e-04 -7.0643118e-03 ...  5.1734028e-03
  -5.3451955e-03  4.5516281e-03]
 [ 1.4687725e-03 -8.3806791e-04 -2.0210645e-03 ...  1.0687255e-03
  -2.9572942e-03  5.0674984e-03]
 [-2.3544501e-03  4.7651760e-05 -6.6494280e-03 ... -3.2191584e-04
  -2.4692491e-03  3.8921135e-03]]


In [40]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (32, 100, 25)          │         1,425 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (32, 100, 1024)        │     3,228,672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (32, 100, 57)          │        58,425 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,288,522 (12.54 MB)

 Trainable params: 3,288,522 (12.54 MB)

 Non-trainable params: 0 (0.00 B)

In [42]:
num_genrate=1000
frist_string='به نام خداوند جان و خرد'
input_eval=[char2index[s]for s in frist_string]
input_eval=tf.expand_dims(input_eval,0)

In [43]:
output[0]

array([[ 2.8175013e-03, -5.3226185e-04,  3.3565252e-03, ...,
        -3.1567621e-03,  6.2571443e-04, -1.2451001e-03],
       [ 7.9092610e-04,  2.5158504e-03,  3.9309915e-04, ...,
        -3.8301460e-03, -2.2878519e-03, -3.6741735e-03],
       [ 2.5701481e-03,  5.7749724e-04,  1.2719432e-03, ...,
        -4.6338914e-03, -1.4856802e-03,  8.8972703e-04],
       ...,
       [-1.7969580e-03,  6.5175665e-04, -7.0643118e-03, ...,
         5.1734028e-03, -5.3451955e-03,  4.5516281e-03],
       [ 1.4687725e-03, -8.3806791e-04, -2.0210645e-03, ...,
         1.0687255e-03, -2.9572942e-03,  5.0674984e-03],
       [-2.3544501e-03,  4.7651760e-05, -6.6494280e-03, ...,
        -3.2191584e-04, -2.4692491e-03,  3.8921135e-03]],
      shape=(100, 57), dtype=float32)

In [44]:
si=tf.random.categorical(output[0],num_samples=1)
si

<tf.Tensor: shape=(100, 1), dtype=int64, numpy=
array([[22],
       [40],
       [37],
       [53],
       [12],
       [ 1],
       [50],
       [44],
       [ 1],
       [40],
       [ 1],
       [55],
       [56],
       [35],
       [ 2],
       [23],
       [19],
       [28],
       [37],
       [34],
       [ 4],
       [42],
       [44],
       [29],
       [30],
       [55],
       [ 6],
       [28],
       [22],
       [ 5],
       [18],
       [43],
       [17],
       [56],
       [56],
       [34],
       [28],
       [54],
       [41],
       [16],
       [37],
       [55],
       [32],
       [49],
       [48],
       [26],
       [52],
       [17],
       [19],
       [53],
       [46],
       [12],
       [ 8],
       [28],
       [53],
       [20],
       [33],
       [ 7],
       [ 9],
       [23],
       [11],
       [29],
       [44],
       [32],
       [46],
       [12],
       [14],
       [38],
       [42],
       [53],
       [ 9],
       [12],
       [10],
   

In [45]:
tf.squeeze(si,axis=-1).numpy()

array([22, 40, 37, 53, 12,  1, 50, 44,  1, 40,  1, 55, 56, 35,  2, 23, 19,
       28, 37, 34,  4, 42, 44, 29, 30, 55,  6, 28, 22,  5, 18, 43, 17, 56,
       56, 34, 28, 54, 41, 16, 37, 55, 32, 49, 48, 26, 52, 17, 19, 53, 46,
       12,  8, 28, 53, 20, 33,  7,  9, 23, 11, 29, 44, 32, 46, 12, 14, 38,
       42, 53,  9, 12, 10, 43, 14, 56, 43, 19, 31, 38, 49, 38, 26, 14, 42,
       30, 15,  4, 53, 30, 12,  1,  8, 44, 51, 27, 18, 33, 29, 51])

In [46]:
''.join(index2char[tf.squeeze(si,axis=-1).numpy()])

'دومژؤ\rُٰ\rو\rگیق ذجصمف:ًُضطگ«صد|ثَتییفصکيةمگعٔٓسچتجژّؤ،صژحغ»؟ذآضُعّؤانًژ؟ؤءَایَجظنٔنساًطب:ژطؤ\r،ُپشثغضپ'

In [47]:
def loss_f(labels,logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels,logits,from_logits=True)
model.compile(optimizer='adam',loss=loss_f)

In [50]:
check_point=tf.keras.callbacks.ModelCheckpoint(filepath='chekponit_khayyam.weights.h5',save_weights_only=True)

In [51]:
history=model.fit(dataset,epochs=100,callbacks=[check_point])

Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 21s 697ms/step - loss: 3.5196
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 78s 2s/step - loss: 2.7747
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 38s 1s/step - loss: 2.4939
Epoch 4/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 24s 748ms/step - loss: 2.3933
Epoch 5/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 20s 665ms/step - loss: 2.3431
Epoch 6/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 54s 2s/step - loss: 2.3087
Epoch 7/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 86s 2s/step - loss: 2.2748
Epoch 8/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 59s 2s/step - loss: 2.2395
Epoch 9/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - loss: 2.2051
Epoch 10/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 39s 1s/step - loss: 2.1732
Epoch 11/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 55s 2s/step - loss: 2.1418
Epoch 12/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 53s 2s/step - loss: 2.1129
Epoch 13/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 82s 2s/step - loss: 2.0866
Epoch 14/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 82s 2s/step - loss: 2.0609
Epoch 15/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 87s 2s/step - loss: 2.