In [132]:
import tensorflow as tf
import numpy as np
import pandas as pd
import time
from tensorflow.keras.models import Sequential,Model
from numpy.lib.recfunctions import join_by
from sympy import sequence



In [133]:
text=open('khayyam.txt','rb').read().decode('utf-8')
text[:10]

'|برخیز بُت'

In [134]:
vocabolaries=sorted(set(text))
vocabolaries[:10]

['\n', '\r', ' ', '!', ':', '|', '\xa0', '«', '»', '،']

In [135]:
len(vocabolaries)

53

In [136]:
char2index={u:i for i,u in enumerate(vocabolaries) }
index2char=np.array(vocabolaries)
char2index

{'\n': 0,
 '\r': 1,
 ' ': 2,
 '!': 3,
 ':': 4,
 '|': 5,
 '\xa0': 6,
 '«': 7,
 '»': 8,
 '،': 9,
 '؟': 10,
 'آ': 11,
 'أ': 12,
 'ئ': 13,
 'ا': 14,
 'ب': 15,
 'ت': 16,
 'ث': 17,
 'ج': 18,
 'ح': 19,
 'خ': 20,
 'د': 21,
 'ذ': 22,
 'ر': 23,
 'ز': 24,
 'س': 25,
 'ش': 26,
 'ص': 27,
 'ض': 28,
 'ط': 29,
 'ظ': 30,
 'ع': 31,
 'غ': 32,
 'ف': 33,
 'ق': 34,
 'ل': 35,
 'م': 36,
 'ن': 37,
 'ه': 38,
 'و': 39,
 'َ': 40,
 'ُ': 41,
 'ِ': 42,
 'ّ': 43,
 'ْ': 44,
 'ٔ': 45,
 'پ': 46,
 'چ': 47,
 'ژ': 48,
 'ک': 49,
 'گ': 50,
 'ۀ': 51,
 'ی': 52}

In [137]:
text_as_integer=np.array([char2index[c] for c in text])
text_as_integer

array([ 5, 15, 23, ..., 10,  1,  0], shape=(22813,))

In [138]:
char_dataset=tf.data.Dataset.from_tensor_slices(text_as_integer)
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>

In [139]:
for i in char_dataset:
    print(index2char[i.numpy()])

|
ب
ر
خ
ی
ز
 
ب
ُ
ت
ا
،
 
ب
ی
ا
 
ز
 
ب
ه
ر
 
د
ل
 
م
ا



|
ح
ل
 
ک
ن
 
ب
ه
 
ج
م
ا
ل
 
خ
و
ی
ش
ت
ن
 
م
ش
ک
ل
 
م
ا



|
ی
ک
 
ک
و
ز
ه
 
ش
ر
ا
ب
 
ت
ا
 
ب
ه
 
ه
م
 
ن
و
ش
 
ک
ن
ی
م



|
ز
آ
ن
 
پ
ی
ش
 
ک
ه
 
ک
و
ز
ه
 
ه
ا
 
ک
ن
ن
د
 
ا
ز
 
گ
ِ
ل
 
م
ا



|
چ
و
ن
 
ع
ه
د
ه
 
ن
م
ی
 
ش
و
د
 
ک
س
ی
 
ف
ر
د
ا
 
ر
ا



|
ح
ا
ل
ی
 
خ
و
ش
 
د
ا
ر
 
ا
ی
ن
 
د
ل
ِ
 
پ
ر
 
س
و
د
ا
 
ر
ا



|
م
ِ
ی
 
ن
و
ش
 
ب
ه
 
م
ا
ه
ت
ا
ب
 
ا
ی
 
م
ا
ه
 
ک
ه
 
م
ا
ه



|
ب
س
ی
ا
ر
 
ب
ت
ا
ب
د
 
و
 
ن
ی
ا
ب
د
 
م
ا
 
ر
ا



|
ق
ر
آ
ن
 
ک
ه
 
م
ه
ی
ن
 
ک
ل
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
گ
ه
 
گ
ا
ه
 
ن
ه
 
ب
ر
 
د
و
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
ب
ر
 
گ
ِ
ر
د
ِ
 
پ
ی
ا
ل
ه
،
 
آ
ی
ت
ی
 
ه
س
ت
 
م
ق
ی
م



|
ک
ا
ن
د
ر
 
ه
م
ه
 
ج
ا
 
م
د
ا
م
 
خ
و
ا
ن
ن
د
 
آ
ن
 
ر
ا



|
گ
ر
 
م
ِ
ی
 
ن
خ
و
ر
ی
 
ط
ع
ن
ه
 
م
ز
ن
 
م
س
ت
ا
ن
 
ر
ا



|
ب
ن
ی
ا
د
 
م
ک
َ
ن
 
ت
و
 
ح
ی
ل
ه
 
و
 
د
س
ت
ا
ن
 
ر
ا



|
ت
و
 
غ
ر
ه
 
ب
د
ا
ن
 
م
ش
و
 
ک
ه
 
م
ِ
ی
 
م
ی
 
ن
خ
و
ر
ی



|
ص
د
 
ل
ق
م
ه
 
خ
و
ر
ی
 
ک
ه
 
م
ِ
ی
 

In [140]:
sequence=char_dataset.batch(30,drop_remainder=True)
sequence

<_BatchDataset element_spec=TensorSpec(shape=(30,), dtype=tf.int64, name=None)>

In [141]:
for i in sequence.take(3):
    print('---->',''.join(index2char[i.numpy()]))

----> |برخیز بُتا، بیا ز بهر دل ما

----> |حل کن به جمال خویشتن مشکل ما
----> 
|یک کوزه شراب تا به هم نوش کن


In [142]:
def sit(batch):
    input_txt=batch[:-1]
    target_txt=batch[1:]
    return input_txt,target_txt
dataset=sequence.map(sit)

In [143]:
dataset

<_MapDataset element_spec=(TensorSpec(shape=(29,), dtype=tf.int64, name=None), TensorSpec(shape=(29,), dtype=tf.int64, name=None))>

In [144]:
for i in dataset.take(1):
    print(i)

(<tf.Tensor: shape=(29,), dtype=int64, numpy=
array([ 5, 15, 23, 20, 52, 24,  2, 15, 41, 16, 14,  9,  2, 15, 52, 14,  2,
       24,  2, 15, 38, 23,  2, 21, 35,  2, 36, 14,  1])>, <tf.Tensor: shape=(29,), dtype=int64, numpy=
array([15, 23, 20, 52, 24,  2, 15, 41, 16, 14,  9,  2, 15, 52, 14,  2, 24,
        2, 15, 38, 23,  2, 21, 35,  2, 36, 14,  1,  0])>)


In [145]:
for i in dataset.take(1):
    print(''.join(index2char[i[0].numpy()]))
    print(''.join(index2char[i[1].numpy()]))


|برخیز بُتا، بیا ز بهر دل ما
برخیز بُتا، بیا ز بهر دل ما



In [146]:
dataset=dataset.batch(64,drop_remainder=True)
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(64, 29), dtype=tf.int64, name=None), TensorSpec(shape=(64, 29), dtype=tf.int64, name=None))>

In [147]:
vocabulary_size=len(vocabolaries)
embding_dim=25
rnn_units=1024

In [148]:
from tensorflow.keras.layers import Embedding,Dense,GRU
model = Sequential()
model.add(Embedding(input_dim=vocabulary_size, output_dim=25)),
model.add(GRU(1024, return_sequences=True)),
model.add(Dense(vocabulary_size))

In [149]:
for input_text,target_text in dataset.take(1):
    output=model.predict(input_text)
    print(output[0])

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step
[[ 0.0022294   0.00161465 -0.00080212 ...  0.00209254 -0.00026548
   0.00288004]
 [-0.00046667  0.00318602 -0.00546724 ... -0.00103332  0.00288738
   0.00453786]
 [-0.00046238  0.00556587 -0.00701558 ...  0.00222482  0.00072457
   0.00899637]
 ...
 [ 0.00406877  0.00141431 -0.00132494 ...  0.0003346   0.00029533
   0.0005728 ]
 [ 0.00543927  0.00239776 -0.00049733 ...  0.00079861 -0.00011603
   0.00428902]
 [ 0.00449047  0.00189215 -0.00154033 ...  0.00036601  0.00455012
   0.00722406]]


In [150]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_18 (Embedding)        │ (32, 29, 25)           │         1,325 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_11 (GRU)                    │ (32, 29, 1024)         │     3,228,672 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (32, 29, 53)           │        54,325 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,284,322 (12.53 MB)

 Trainable params: 3,284,322 (12.53 MB)

 Non-trainable params: 0 (0.00 B)

In [151]:
output[0]

array([[ 0.0022294 ,  0.00161465, -0.00080212, ...,  0.00209254,
        -0.00026548,  0.00288004],
       [-0.00046667,  0.00318602, -0.00546724, ..., -0.00103332,
         0.00288738,  0.00453786],
       [-0.00046238,  0.00556587, -0.00701558, ...,  0.00222482,
         0.00072457,  0.00899637],
       ...,
       [ 0.00406877,  0.00141431, -0.00132494, ...,  0.0003346 ,
         0.00029533,  0.0005728 ],
       [ 0.00543927,  0.00239776, -0.00049733, ...,  0.00079861,
        -0.00011603,  0.00428902],
       [ 0.00449047,  0.00189215, -0.00154033, ...,  0.00036601,
         0.00455012,  0.00722406]], shape=(29, 53), dtype=float32)

In [152]:
si=tf.random.categorical(output[0],num_samples=1)
si

<tf.Tensor: shape=(29, 1), dtype=int64, numpy=
array([[39],
       [52],
       [38],
       [36],
       [51],
       [29],
       [ 6],
       [31],
       [37],
       [48],
       [ 7],
       [43],
       [25],
       [10],
       [31],
       [ 5],
       [11],
       [51],
       [ 6],
       [20],
       [44],
       [21],
       [30],
       [52],
       [41],
       [ 1],
       [47],
       [38],
       [19]])>

In [153]:
tf.squeeze(si,axis=1).numpy()

array([39, 52, 38, 36, 51, 29,  6, 31, 37, 48,  7, 43, 25, 10, 31,  5, 11,
       51,  6, 20, 44, 21, 30, 52, 41,  1, 47, 38, 19])

In [154]:
''.join(index2char[tf.squeeze(si,axis=1).numpy()])

'ویهمۀط\xa0عنژ«ّس؟ع|آۀ\xa0خْدظیُ\rچهح'

In [161]:
def loss_f(labels,logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels,logits,from_logits=True)
model.compile(optimizer='adam',loss=loss_f)

In [162]:
check_point=tf.keras.callbacks.ModelCheckpoint(filepath='chekponit_khayyam.weights.h5',save_weights_only=True)

In [163]:
history=model.fit(dataset,epochs=10,callbacks=[check_point])

Epoch 1/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 129ms/step - loss: 4.2698
Epoch 2/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - loss: 3.8802
Epoch 3/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - loss: 3.7390
Epoch 4/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 130ms/step - loss: 3.2374
Epoch 5/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 131ms/step - loss: 3.1167
Epoch 6/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 143ms/step - loss: 3.0410
Epoch 7/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 130ms/step - loss: 2.9357
Epoch 8/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - loss: 2.7697
Epoch 9/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 135ms/step - loss: 2.6219
Epoch 10/10
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - loss: 2.5574
