In [109]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [110]:
data=pd.read_csv('cardio_train.csv')
data.head()

id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0

In [111]:
data.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [112]:
x=data.iloc[:,1:-1]
y=data.iloc[:,-1]

In [113]:
from sklearn.preprocessing import MinMaxScaler
scler=MinMaxScaler()
x=scler.fit_transform(data)
x

array([[0.00000000e+00, 5.88075881e-01, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.00001000e-05, 7.30158730e-01, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.00002000e-05, 6.24003097e-01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [9.99970000e-01, 6.40185830e-01, 1.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.99990000e-01, 9.00735579e-01, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 7.54316686e-01, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]],
      shape=(70000, 13))

In [114]:
y = pd.get_dummies(y)
y

0      1
0       True  False
1      False   True
2      False   True
3      False   True
4       True  False
...      ...    ...
69995   True  False
69996  False   True
69997  False   True
69998  False   True
69999   True  False

[70000 rows x 2 columns]

In [115]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=3234)
print("train: shape",x_train.shape,y_train.shape)
print("test shape:",x_test.shape,y_test.shape,)

train: shape (52500, 13) (52500, 2)
test shape: (17500, 13) (17500, 2)


In [116]:
np.shape(x)

(70000, 13)

In [117]:
model=tf.keras.models.Sequential([
        tf.keras.layers.Dense(13, activation='relu',input_shape=(13,)),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')

])

C:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [118]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),metrics=[tf.keras.metrics.CategoricalAccuracy()])


In [119]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=800,verbose=3)


Epoch 1/10
Epoch 2/10
Epoch 3/10
Epoch 4/10
Epoch 5/10
Epoch 6/10
Epoch 7/10
Epoch 8/10
Epoch 9/10
Epoch 10/10


In [120]:
from sklearn.ensemble import RandomForestClassifier
yr=data.iloc[:,-1]

In [121]:
np.unique(yr,return_counts=True)

(array([0, 1]), array([35021, 34979]))

In [122]:
m=RandomForestClassifier(n_estimators=200)
xr_train,xr_test,yr_train,yr_test=train_test_split(x,yr,random_state=3234)

In [123]:
m.fit(xr_train,yr_train)

RandomForestClassifier(n_estimators=200)

In [125]:
from sklearn.metrics import classification_report
y_pred=m.predict(xr_test)
print(classification_report(yr_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8713
           1       1.00      1.00      1.00      8787

    accuracy                           1.00     17500
   macro avg       1.00      1.00      1.00     17500
weighted avg       1.00      1.00      1.00     17500



In [126]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(13, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dense(30, activation='relu'),
     tf.keras.layers.Dense(60, activation='relu'),
     tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')

])

C:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [128]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),metrics=[tf.keras.metrics.CategoricalAccuracy()])


In [129]:
model.fit(x_train,y_train,epochs=500,validation_data=(x_test,y_test),batch_size=300)


Epoch 1/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.9739 - loss: 0.1327 - val_categorical_accuracy: 1.0000 - val_loss: 3.8680e-04
Epoch 2/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 1.0000 - loss: 1.6492e-04 - val_categorical_accuracy: 1.0000 - val_loss: 6.1390e-05
Epoch 3/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 1.0000 - loss: 2.9571e-05 - val_categorical_accuracy: 1.0000 - val_loss: 1.5013e-05
Epoch 4/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 1.0000 - loss: 9.7816e-06 - val_categorical_accuracy: 1.0000 - val_loss: 7.0890e-06
Epoch 5/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 1.0000 - loss: 5.0638e-06 - val_categorical_accuracy: 1.0000 - val_loss: 4.1575e-06
Epoch 6/500
175/175 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 1.0000 - loss: 3.1088e-06 - val_categorical_accuracy: 1.0000 - val_loss: 2.7212e-06
Epoch 7/500
175/175 ━━━━━━━━━━━━━━━━━━

In [130]:
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_65 (Dense)                │ (None, 13)             │           182 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_66 (Dense)                │ (None, 30)             │           420 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_67 (Dense)                │ (None, 60)             │         1,860 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_68 (Dense)                │ (None, 25)             │         1,525 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_69 (Dense)                │ (None, 2)              │            52 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,119 (47.34 KB)

 Trainable params: 4,039 (15.78 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 8,080 (31.57 KB)

In [132]:
np.argmax(model.predict(x_test)[0])

547/547 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step


np.int64(1)

In [135]:
np.argmax(model.predict(x_test)[2])


547/547 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step


np.int64(0)

In [138]:
model.predict(x_test)[7]


547/547 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step


array([8.547094e-16, 1.000000e+00], dtype=float32)