In [1]:
import os

import  numpy as np
import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Conv2D,MaxPool2D,Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
import tensorflow as tf
from mnist_datasets import MNISTLoader

In [2]:
import os
print(os.listdir())

['.git', '.idea', '.venv', '1_Perceptron.ipynb', 'BNK.ipynb', 'cardio_train.csv', 'GPT.ipynb', 'heart.ipynb', 'Image Processing.ipynb', 'main.py', 'MNISCNN.ipynb', 'mnist.npz', 'testing.csv', 'TFkerasMINST.ipynb', 'training.csv', '__pycache__']


In [3]:
data = np.load("mnist.npz")
print(data.files)

['x_test', 'x_train', 'y_train', 'y_test']


In [4]:
x_train = data['x_train']
y_train = data['y_train']
x_test  = data['x_test']
y_test  = data['y_test']

In [5]:
np.shape(x_train)

(60000, 28, 28)

In [6]:
x_train=x_train/255
x_test=x_test/255


In [7]:
x_train[1000]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [8]:
x_train=np.expand_dims(x_train,axis=3)

In [9]:
np.shape(x_train)

(60000, 28, 28, 1)

In [10]:
x_train[1000]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [11]:
x_test=np.expand_dims(x_test,axis=3)

In [12]:
model=Sequential([
    Conv2D(filters=10,kernel_size=(3,3),input_shape=(28,28,1)),
    MaxPool2D(pool_size=(2,2),strides=(2,2)),
     Conv2D(filters=2,kernel_size=(3,3)),
    MaxPool2D(pool_size=(2,2),strides=(2,2)),
    Flatten(),
    Dense(128,activation="relu"),
    Dense(10,activation="softmax"),
])

C:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 10)     │           100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 2)      │           182 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 2)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │         6,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,100 (31.64 KB)

 Trainable params: 8,100 (31.64 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile("adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [15]:
y_train_o=to_categorical(y_train)
y_test_o=to_categorical(y_test)

In [16]:
y_train_o[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [17]:
history=model.fit(x_train,y_train_o,epochs=10,batch_size=300,validation_data=(x_test,y_test_o))

Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step - accuracy: 0.7722 - loss: 0.7716 - val_accuracy: 0.9151 - val_loss: 0.2787
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 6s 28ms/step - accuracy: 0.9242 - loss: 0.2533 - val_accuracy: 0.9397 - val_loss: 0.1949
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.9431 - loss: 0.1887 - val_accuracy: 0.9517 - val_loss: 0.1584
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9530 - loss: 0.1557 - val_accuracy: 0.9583 - val_loss: 0.1321
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9592 - loss: 0.1364 - val_accuracy: 0.9607 - val_loss: 0.1249
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9629 - loss: 0.1228 - val_accuracy: 0.9645 - val_loss: 0.1145
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9661 - loss: 0.1114 - val_accuracy: 0.9671 - val_loss: 0.1068
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 6s 28ms/step - accuracy: 0.9687 - loss: 0.1039 - val_accuracy

In [18]:
history